[tool.poetry]
name = "dias-uteis"
version = "0.1.2"
description = ""
authors = ["renanmoretto <himynameisrenan@outlook.com>"]
readme = "README.md"
packages = [{include = "dias_uteis"}]
repository = "https://github.com/renanmoretto/dias_uteis"
[tool.poetry.dependencies]
python = "^3.6"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.26.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
